### ISSUE TITLE
I have ported this library to Xamarin

### ISSUE THREAD

**Issue by blounty** [uzysjung/UzysSlideMenu#1]
Hey there,

I just wanted to let you know that i have ported this project over to Xamarin. Hope this is ok with you. I have linked back to your repo from the docs.

Thanks

Alex

**Comment by uzysjung** [comment]
It's OK. Please Let me know you're done :)

Uzys.

**Comment by blounty** [comment]
All done . :)

https://github.com/blounty/Xamarin.UzysSlideMenu
