### ISSUE TITLE
Blocks are called twice per menu usage

### ISSUE THREAD

**Issue by tooluser** [uzysjung/UzysSlideMenu#5]
Thanks for the lovely control. I'm going to file a few issues - things I've noticed as I've started working with it.

When the menu is tapped to open it, it calls the associated item's block. When the menu is tapped again to select an item, that item's block is called as well. Thus each time the menu is used, two blocks are called. This means that the blocks have to handle two different things: when I am tapped to open the menu, and when I am tapped to actually select me.

**Comment by uzysjung** [comment]
you can check menuState property in item's block.

I add example to Development Branch.

Thanks.
