### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by tooluser** [uzysjung/UzysSlideMenu#6]
Howdy!

I noticed that in a few places, code is reused identically between the animated and non-animated versions of a method. This is easily gotten around, though: put the shared code in a block, and call it, thus:

-(void)showIconMenu:(BOOL)animation {
 . . . (put shared code in block here) 
    if(animation) {
        [UIView animateWithDuration:0.3 delay:0 options:UIViewAnimationOptionBeginFromCurrentState|UIViewAnimationOptionTransitionCrossDissolve|UIViewAnimationOptionCurveEaseOut|UIViewAnimationOptionAllowAnimatedContent animations:^{
            showIconMenuBlock();
        } completion:^(BOOL finished) {
            self.state = STATE_ICON_MENU;
        }];
    } else {
        showIconMenuBlock();
        self.state = STATE_ICON_MENU;
    }
}

Thanks!

**Comment by uzysjung** [comment]
Thank you for your opinion. 

shared code only uses 2 place.
I would prefer keep it duplication. Because of code readability.

**Comment by tooluser** [comment]
. . . . o.O

**Comment by uzysjung** [comment]
I apply things you issued to Development Branch. 

Thanks~
